- Kvantum/themes/kvthemes/KvArc/KvArc.kvconfig
I've adjusted the ItemView header to remove the top and left borders. But the right border is also removed?
> Adjust font colours and sizes to more closely reflect Arc

- Kvantum/kvantummanager/data/kvantummanager.desktop
btw, Will there be possibility to fully localize this app?
> translated *.desktop to Polish

- Kvantum/style/Kvantum.cpp
...and second part for Issue #128
> Link 'respect_DE' and composite settings only for Unity. Issue #128

- Kvantum/kvantummanager/KvantumManager.cpp
- Kvantum/kvantummanager/kvantummanager.ui
- Kvantum/style/Kvantum.cpp
- Kvantum/style/themeconfig/ThemeConfig.cpp
- Kvantum/style/themeconfig/specs.h
- Kvantum/themes/kvthemes/KvArc/KvArc.kvconfig
- Kvantum/themes/kvthemes/KvArcDark/KvArcDark.kvconfig
> Add option to hide combo popup menu checkboxes.

- Kvantum/INSTALL
It has been quite some time that kvantum is in the official arch repo. Hope the changes are correct.
> Updating Arch Install method

- Kvantum/style/Kvantum.cpp
Credit to trialuser02 at https://sourceforge.net/p/qt5ct/tickets/65/
Tested, fixes #148
> Add QProxyStyle support

- Kvantum/style/themeconfig/ThemeConfig.cpp
Hello,
Tsujan may you merge this minor FreeBSD related fix?
Thank you.
> Fix build on FreeBSD.

- Kvantum/INSTALL.md
This makes it much easier for people to read on GitHub.
> Convert INSTALL to markdown

- Kvantum/INSTALL.md
I have built packages for Fedora. If you want you can include those packages in INSTALL.md.
> Include my Copr Repository Pacakges for Fedora in INSTALL.md

- Kvantum/README.md
I noticed some flaws in your README, so I decided to make it a bit better.
> Revamped README

- Kvantum/INSTALL.md
- Kvantum/README.md
It was very cluttered and it had a lot of issues in general, so I revamped it to make it easier to understand. **MAKE SURE THOSE PACKAGES WORK BECAUSE I HAVE NO CLUE HOW TO SEARCH FOR PACKAGES.**
> Revamped INSTALL.md

- Kvantum/kvantummanager/data/translations/kvantummanager_fi.ts
- Kvantum/kvantumpreview/data/translations/kvantumpreview_fi.ts
> Finnish translations

- Kvantum/style/themeconfig/ThemeConfig.cpp
Hi,
And here I am again porting your software to NetBSD :)
This was a request from a user that I packaged yesterday, still a work-in-progress but, I hope to merge it the near future.
Cheers!
> Allow build on NetBSD

- Kvantum/INSTALL.md
> Added instructions for installation on Solus

- Kvantum/kvantummanager/data/translations/kvantummanager_es.ts
I have translated 5 messages that had not been translated into Spanish
> Translation of untranslated messages (to Spanish)

- Kvantum/kvantummanager/data/translations/kvantummanager_cs.ts
Hello.
I found out that such a beautiful project as Kvantum Manger is only slightly translated into English. And that's a pity. So I decided to finish localization of Kvantum Manager into Czech language. I would like to contribute to the Kvantum Manager Project. I would be glad if you would include my translations in this Pull Request in your repository.
What do you think?
> Completion of Czech localization of Kvantum Manager

- Kvantum/kvantummanager/data/translations/kvantummanager_cs.ts
Hi,
I've updated the Czech translations of Kvantum Manager, and I marked the translated parts as translated :)
> Update of the Czech translation

- Kvantum/kvantummanager/data/translations/kvantummanager_cs.ts
> Update of Czech translations

- Kvantum/kvantumpreview/data/translations/kvantumpreview_cs.ts
Hello,
I finished the Czech translations for Kvantum Preview :)
> Update of Czech Translation for Kvantum Preview

- .mailmap
- Kvantum/README.md
- Remaps our old emails/aliases to the current.
From:
```
❯ git shortlog -sne --all
1323  Tsu Jan <tsujan2000@gmail.com>
176  tsujan <tsujan2000@gmail.com>
[...]
8  TheMainOne <50847364+TheEvilSkeleton@users.noreply.github.com>
```
To:
```
❯ git shortlog -sne --all
1499  Tsu Jan <tsujan2000@gmail.com>
[...]
9  TheEvilSkeleton <theevilskeleton@riseup.net>
```
- Changes my old username to the current in README.
> Fix commit authors
